apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  values:
    profile: ambient
    global:
      logAsJson: true
    meshConfig:
      serviceSettings:
        - settings:
            clusterLocal: true
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"
      enableTracing: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cni
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  values:
    profile: ambient
    cni:
      cniConfName: "10-aws.conflist"
      ambient:
        ipv6: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ztunnel
  namespace: kube-system
spec:
  dependsOn:
    - name: cni
  chart:
    spec:
      chart: ztunnel
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s