apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: external-dns
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare
  dataFrom:
  - extract:
      key: stackai/production/cloudflare