apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-database-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-database-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-database-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-jwt-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-jwt-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-jwt-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-dashboard-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-dashboard-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-dashboard-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-realtime-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-realtime-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-realtime-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-meta-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-meta-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-meta-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-analytics-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-analytics-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-analytics-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-storage-secret
  namespace: supabase
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: supabase-storage-secret
  dataFrom:
  - extract:
      key: stackai/production/supabase-storage-secret