apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metrics-server
    namespace: kube-system
spec:
    chart:
        spec:
            chart: metrics-server
            version: 3.13.0
            sourceRef:
                kind: HelmRepository
                name: metrics-server
                namespace: kube-system
    interval: 1h0m0s